[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-weak_framework CoreHaptics"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-weak_framework CoreHaptics"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-lz"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-lz"]
